# Sanoid — ZFS Snapshot Management
# Manages automated snapshots and pruning for rpool/data and its children.
# Config is fully declarative; /etc/sanoid/sanoid.conf is generated by Nix.
{...}: {
  services.sanoid = {
    enable = true;

    # Run every 15 minutes (systemd calendar format).
    interval = "*:0/15";

    datasets."rpool/data" = {
      use_template = ["production"];
      recursive = true;
      process_children_only = true;
    };

    # ── Active template ───────────────────────────────────────────────────
    templates.production = {
      frequently = 0;
      hourly = 36;
      daily = 30;
      monthly = 3;
      yearly = 0;
      autosnap = true;
      autoprune = true;
    };

    # ── Reference templates (not assigned to any dataset) ─────────────────
    # Kept here for documentation / future use.
    templates.demo = {
      daily = 60;
    };

    templates.ignore = {
      autoprune = false;
      autosnap = false;
      monitor = false;
    };

    # backup — intended for datasets receiving replicated snapshots.
    # Monitoring thresholds and script hooks are freeform fields accepted
    # by the template submodule even though they aren't typed options.
    templates.backup = {
      autosnap = false;
      autoprune = true;
      frequently = 0;
      hourly = 30;
      daily = 90;
      monthly = 12;
      yearly = 0;
      hourly_warn = 2880;
      hourly_crit = 3600;
      daily_warn = 48;
      daily_crit = 60;
    };

    # hotspare — tighter monitoring thresholds for hot-spare replication targets.
    templates.hotspare = {
      autosnap = false;
      autoprune = true;
      frequently = 0;
      hourly = 30;
      daily = 90;
      monthly = 3;
      yearly = 0;
      hourly_warn = "4h";
      hourly_crit = "6h";
      daily_warn = "2d";
      daily_crit = "4d";
    };

    # scripts — placeholder showing how to attach pre/post hooks to snapshots.
    templates.scripts = {
      pre_snapshot_script = "/path/to/script.sh";
      post_snapshot_script = "/path/to/script.sh";
      pre_pruning_script = "/path/to/script.sh";
      pruning_script = "/path/to/script.sh";
      script_timeout = 5;
    };
  };
}
