# Sanoid — ZFS Snapshot Management
# Manages automated snapshots and pruning for rpool/data and its children.
# Config is fully declarative; /etc/sanoid/sanoid.conf is generated by Nix.
{
  config,
  lib,
  pkgs,
  ...
}: let
  # Mirrors the INI serialisation from the upstream NixOS sanoid module so that
  # /etc/sanoid/sanoid.conf stays in sync for interactive `sanoid` invocations.
  mkValueString = v:
    if lib.isList v
    then lib.concatStringsSep "," v
    else lib.generators.mkValueStringDefault {} v;

  mkKeyValue = k: v:
    if v == null || builtins.elem k ["processChildrenOnly" "useTemplate"]
    then ""
    else lib.generators.mkKeyValueDefault {inherit mkValueString;} "=" k v;
in {
  # Expose sanoid/syncoid/findoid CLIs in PATH for manual runs.
  environment.systemPackages = [pkgs.sanoid];

  services.sanoid = {
    enable = true;

    # Run every 15 minutes (systemd calendar format).
    interval = "*:0/15";

    datasets."rpool/data" = {
      use_template = ["production"];
      recursive = true;
      process_children_only = true;
    };

    # ── Active template ───────────────────────────────────────────────────
    templates.production = {
      frequently = 0;
      hourly = 36;
      daily = 30;
      monthly = 3;
      yearly = 0;
      autosnap = true;
      autoprune = true;
    };

    # ── Reference templates (not assigned to any dataset) ─────────────────
    # Kept here for documentation / future use.
    templates.demo = {
      daily = 60;
    };

    templates.ignore = {
      autoprune = false;
      autosnap = false;
      monitor = false;
    };

    # backup — intended for datasets receiving replicated snapshots.
    # Monitoring thresholds and script hooks are freeform fields accepted
    # by the template submodule even though they aren't typed options.
    templates.backup = {
      autosnap = false;
      autoprune = true;
      frequently = 0;
      hourly = 30;
      daily = 90;
      monthly = 12;
      yearly = 0;
      hourly_warn = 2880;
      hourly_crit = 3600;
      daily_warn = 48;
      daily_crit = 60;
    };

    # hotspare — tighter monitoring thresholds for hot-spare replication targets.
    templates.hotspare = {
      autosnap = false;
      autoprune = true;
      frequently = 0;
      hourly = 30;
      daily = 90;
      monthly = 3;
      yearly = 0;
      hourly_warn = "4h";
      hourly_crit = "6h";
      daily_warn = "2d";
      daily_crit = "4d";
    };

    # scripts — placeholder showing how to attach pre/post hooks to snapshots.
    templates.scripts = {
      pre_snapshot_script = "/path/to/script.sh";
      post_snapshot_script = "/path/to/script.sh";
      pre_pruning_script = "/path/to/script.sh";
      pruning_script = "/path/to/script.sh";
      script_timeout = 5;
    };
  };

  # Run the service as root rather than under DynamicUser.
  # DynamicUser creates an ephemeral user that doesn't exist in /etc/passwd,
  # which causes `zfs allow sanoid …` (ExecStartPre/ExecStopPost) to log
  # "invalid user/group sanoid" on every run. Root already has full ZFS
  # permissions, so the delegation wrappers are redundant and suppressed.
  systemd.services.sanoid.serviceConfig = {
    DynamicUser = lib.mkForce false;
    User = lib.mkForce "root";
    Group = lib.mkForce "root";
    ExecStartPre = lib.mkForce [];
    ExecStopPost = lib.mkForce [];
  };

  # The NixOS sanoid module generates the config in the Nix store and passes it
  # via --configdir, so /etc/sanoid/sanoid.conf is never created. This regenerates
  # the same INI from config.services.sanoid.settings (the merged dataset/template
  # attrset) so that manual `sudo sanoid` invocations find the config at the
  # standard path without needing --configdir.
  environment.etc."sanoid/sanoid.conf".text =
    lib.generators.toINI {inherit mkKeyValue;} config.services.sanoid.settings;
}
